name: Auto Deploy to SFTP

on:
  push:
    branches:
      - main  # Ganti dengan branch yang ingin di-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: echo "Host is ${{ secrets.SFTP_HOST }}"

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "."  # Folder yang akan dikirim
          target: "/web"  # Ganti dengan path tujuan di server
          strip_components: 1  # Menghindari nested folder
